live_config_reload = true

[cursor.style]
blinking = "Always"
shape = "Beam"

[font]
size = 11.0

[font.bold]
family = "Iosevka Term SS04"
style = "Bold"

[font.bold_italic]
family = "Iosevka Term SS04"
style = "Bold Italic"

[font.italic]
family = "Iosevka Term SS04"
style = "Italic"

[font.normal]
family = "Iosevka Term SS04"
style = "Medium"

[scrolling]
history = 0

[shell]
program = "tmux"

[window]
decorations = "none"
dynamic_padding = true
opacity = 1.0
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5
